// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApproveTaskReq struct {
	Action  string `json:"action" validate:"required,oneof=approve reject"`
	Comment string `json:"comment,optional"`
}

type CommonResp struct {
	Message string `json:"message"`
}

// SetProjectPmReq: chỉ định PM mới cho dự án.
type SetProjectPmReq struct {
	UserId string `json:"user_id" validate:"required"`
}

type CreateMeetingReq struct {
	Title          string   `json:"title" validate:"required,max=300"`
	Type           string   `json:"type" validate:"required,oneof=review standup board other"`
	StartTime      string   `json:"start_time" validate:"required"`
	EndTime        string   `json:"end_time" validate:"required"`
	Location       string   `json:"location,optional"`
	MeetingUrl     string   `json:"meeting_url,optional"`
	ProjectId      string   `json:"project_id,optional"`
	AttendeeIds    []string `json:"attendee_ids,optional"`
	IsRecurring    bool     `json:"is_recurring,optional"`
	RecurrenceRule string   `json:"recurrence_rule,optional"`
}

type CreatePhaseReq struct {
	Name      string  `json:"name" validate:"required,max=200"`
	Weight    float64 `json:"weight" validate:"required,min=1,max=100"`
	StartDate string  `json:"start_date,optional"`
	EndDate   string  `json:"end_date,optional"`
	SortOrder int     `json:"sort_order,optional"`
}

type CreateProjectReq struct {
	WorkspaceId string  `json:"workspace_id,optional"`
	Code        string  `json:"code" validate:"required,max=20"`
	Name        string  `json:"name" validate:"required,max=300"`
	Type        string  `json:"type" validate:"required"`
	Description string  `json:"description,optional"`
	StartDate   string  `json:"start_date" validate:"required"`
	EndDate     string  `json:"end_date" validate:"required"`
	BonusPool   float64 `json:"bonus_pool,optional"`
}

type AddProjectMemberReq struct {
	UserId      string  `json:"user_id" validate:"required"`
	BonusAmount float64 `json:"bonus_amount,optional"`
}

type ProjectMemberResp struct {
	Id          string  `json:"id"`
	Username    string  `json:"username"`
	FullName    string  `json:"full_name"`
	Email       string  `json:"email"`
	Role        string  `json:"role"`
	ProjectRole string  `json:"project_role"`
	Avatar      string  `json:"avatar,omitempty"`
	BonusAmount float64 `json:"bonus_amount"`
}

type CreateTaskReq struct {
	PhaseId        string  `json:"phase_id" validate:"required"`
	Title          string  `json:"title" validate:"required,max=500"`
	Description    string  `json:"description,optional"`
	AssigneeId     string  `json:"assignee_id,optional"`
	Priority       string  `json:"priority" validate:"required,oneof=low medium high urgent"`
	DueDate        string  `json:"due_date,optional"`
	EstimatedHours float64 `json:"estimated_hours,optional"`
}

type CreateWorkspaceReq struct {
	Name        string `json:"name" validate:"required,max=200"`
	Description string `json:"description,optional"`
	Color       string `json:"color,optional"`
}

type IdPathReq struct {
	Id string `path:"id"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Token     string   `json:"token"`
	ExpiresAt int64    `json:"expires_at"`
	User      UserInfo `json:"user"`
}

type MeetingListResp struct {
	Total    int64         `json:"total"`
	Meetings []MeetingResp `json:"meetings"`
}

type MeetingResp struct {
	Id          string     `json:"id"`
	Title       string     `json:"title"`
	Type        string     `json:"type"`
	Status      string     `json:"status"`
	StartTime   string     `json:"start_time"`
	EndTime     string     `json:"end_time"`
	Location    string     `json:"location,omitempty"`
	MeetingUrl  string     `json:"meeting_url,omitempty"`
	ProjectId   string     `json:"project_id,omitempty"`
	ProjectName string     `json:"project_name,omitempty"`
	OrganizerId string     `json:"organizer_id"`
	Attendees   []UserInfo `json:"attendees"`
	Notes       string     `json:"notes,omitempty"`
	CreatedAt   string     `json:"created_at"`
}

type NotificationResp struct {
	Id        string `json:"id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	IsRead    bool   `json:"is_read"`
	RefId     string `json:"ref_id,omitempty"`
	RefType   string `json:"ref_type,omitempty"`
	CreatedAt string `json:"created_at"`
}

type PhaseResp struct {
	Id        string  `json:"id"`
	ProjectId string  `json:"project_id"`
	Name      string  `json:"name"`
	Weight    float64 `json:"weight"`
	Progress  float64 `json:"progress"`
	StartDate string  `json:"start_date,omitempty"`
	EndDate   string  `json:"end_date,omitempty"`
	SortOrder int     `json:"sort_order"`
	TaskCount int     `json:"task_count"`
}

type ProjectListResp struct {
	Total    int64         `json:"total"`
	Projects []ProjectResp `json:"projects"`
}

type ProjectResp struct {
	Id             string  `json:"id"`
	Code           string  `json:"code"`
	Name           string  `json:"name"`
	Type           string  `json:"type"`
	Status         string  `json:"status"`
	RagStatus      string  `json:"rag_status"`
	RagOverride    bool    `json:"rag_override"`
	Progress       float64 `json:"progress"`
	StartDate      string  `json:"start_date"`
	EndDate        string  `json:"end_date"`
	PmId           string  `json:"pm_id"`
	PmName         string  `json:"pm_name"`
	MemberCount    int     `json:"member_count"`
	TaskCount      int     `json:"task_count"`
	WorkspaceId    string  `json:"workspace_id,omitempty"`
	BonusPool      float64 `json:"bonus_pool"`
	BonusAllocated float64 `json:"bonus_allocated"`
	CreatedAt      string  `json:"created_at"`
}

type TaskCommentReq struct {
	Content string `json:"content" validate:"required"`
}

type TaskCommentResp struct {
	Id        string   `json:"id"`
	TaskId    string   `json:"task_id"`
	AuthorId  string   `json:"author_id"`
	Author    UserInfo `json:"author"`
	Content   string   `json:"content"`
	CreatedAt string   `json:"created_at"`
}

type TaskResp struct {
	Id             string         `json:"id"`
	ProjectId      string         `json:"project_id"`
	PhaseId        string         `json:"phase_id"`
	ParentId       string         `json:"parent_id,omitempty"`
	Title          string         `json:"title"`
	Description    string         `json:"description,omitempty"`
	Status         string         `json:"status"`
	Priority       string         `json:"priority"`
	AssigneeId     string         `json:"assignee_id,omitempty"`
	AssigneeName   string         `json:"assignee_name,omitempty"`
	AssigneeAvatar string         `json:"assignee_avatar,omitempty"`
	DueDate        string         `json:"due_date,omitempty"`
	EstimatedHours float64        `json:"estimated_hours"`
	ActualHours    float64        `json:"actual_hours"`
	IsOverdue      bool           `json:"is_overdue"`
	ColumnPosition int            `json:"column_position"`
	CreatedBy      string         `json:"created_by,omitempty"`
	Assignees      []TaskAssignee `json:"assignees"`
	DoneCount      int            `json:"done_count"`
	AssigneeCount  int            `json:"assignee_count"`
	CreatedAt      string         `json:"created_at"`
}

type TaskAssignee struct {
	Id       string `json:"id"`
	FullName string `json:"full_name"`
	Avatar   string `json:"avatar,omitempty"`
	IsDone   bool   `json:"is_done"`
}

type AddTaskAssigneeReq struct {
	UserId string `json:"user_id" validate:"required"`
}

type MyProgressReq struct {
	Done bool `json:"done"`
}

type UpdateMeetingNotesReq struct {
	Notes string `json:"notes" validate:"required"`
}

type UpdateRagReq struct {
	RagStatus string `json:"rag_status" validate:"required,oneof=green amber red"`
	RagNote   string `json:"rag_note,optional"`
}

type UpdateTaskStatusReq struct {
	Status string `json:"status" validate:"required,oneof=new in_progress pending_review done rejected"`
}

type UserInfo struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Role     string `json:"role"`
	Avatar   string `json:"avatar,omitempty"`
}

// UpdateProfileReq: người dùng tự sửa hồ sơ của mình.
type UpdateProfileReq struct {
	FullName string `json:"full_name" validate:"required,max=200"`
	Phone    string `json:"phone,optional"`
}

// ChangePasswordReq: đổi mật khẩu (phải xác nhận mật khẩu hiện tại).
type ChangePasswordReq struct {
	CurrentPassword string `json:"current_password" validate:"required"`
	NewPassword     string `json:"new_password" validate:"required,min=6"`
}

type WorkspaceResp struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Color        string `json:"color"`
	OwnerId      string `json:"owner_id"`
	ProjectCount int    `json:"project_count"`
	CreatedAt    string `json:"created_at"`
}

// ─── Cấu hình kênh thông báo (Telegram / Zalo) ──────────────────

// NotificationConfigResp: cấu hình hệ thống (Admin). Không trả token thô,
// chỉ cho biết đã thiết lập hay chưa.
type NotificationConfigResp struct {
	TelegramEnabled  bool `json:"telegram_enabled"`
	TelegramTokenSet bool `json:"telegram_token_set"`
	ZaloEnabled      bool `json:"zalo_enabled"`
	ZaloTokenSet     bool `json:"zalo_token_set"`
}

// UpdateNotificationConfigReq: token để trống = giữ nguyên token cũ.
type UpdateNotificationConfigReq struct {
	TelegramEnabled  bool   `json:"telegram_enabled"`
	TelegramBotToken string `json:"telegram_bot_token,optional"`
	ZaloEnabled      bool   `json:"zalo_enabled"`
	ZaloOaToken      string `json:"zalo_oa_token,optional"`
}

// NotificationSettingsResp: tuỳ chọn nhận thông báo của chính người dùng.
type NotificationSettingsResp struct {
	TelegramChatId string `json:"telegram_chat_id"`
	ZaloUserId     string `json:"zalo_user_id"`
	TelegramOn     bool   `json:"telegram_on"`
	ZaloOn         bool   `json:"zalo_on"`
	NotifyAssigned bool   `json:"notify_assigned"`
	NotifyReview   bool   `json:"notify_review"`
	NotifyDecision bool   `json:"notify_decision"`
	NotifyComment  bool   `json:"notify_comment"`
}

type UpdateNotificationSettingsReq struct {
	TelegramChatId string `json:"telegram_chat_id,optional"`
	ZaloUserId     string `json:"zalo_user_id,optional"`
	TelegramOn     bool   `json:"telegram_on"`
	ZaloOn         bool   `json:"zalo_on"`
	NotifyAssigned bool   `json:"notify_assigned"`
	NotifyReview   bool   `json:"notify_review"`
	NotifyDecision bool   `json:"notify_decision"`
	NotifyComment  bool   `json:"notify_comment"`
}
