// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "github.com/mocatech/erp/internal/handler/auth"
	meeting "github.com/mocatech/erp/internal/handler/meeting"
	notification "github.com/mocatech/erp/internal/handler/notification"
	phase "github.com/mocatech/erp/internal/handler/phase"
	project "github.com/mocatech/erp/internal/handler/project"
	task "github.com/mocatech/erp/internal/handler/task"
	user "github.com/mocatech/erp/internal/handler/user"
	workspace "github.com/mocatech/erp/internal/handler/workspace"
	"github.com/mocatech/erp/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Đăng nhập
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// Làm mới token
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					// Danh sách người dùng
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: user.ListUsersHandler(serverCtx),
				},
				{
					// Hồ sơ của chính mình
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: user.GetMeHandler(serverCtx),
				},
				{
					// Cập nhật hồ sơ (tên, số điện thoại)
					Method:  http.MethodPut,
					Path:    "/me",
					Handler: user.UpdateProfileHandler(serverCtx),
				},
				{
					// Đổi mật khẩu
					Method:  http.MethodPut,
					Path:    "/me/password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					// Danh sách cuộc họp
					Method:  http.MethodGet,
					Path:    "/meetings",
					Handler: meeting.ListMeetingsHandler(serverCtx),
				},
				{
					// Tạo lịch họp
					Method:  http.MethodPost,
					Path:    "/meetings",
					Handler: meeting.CreateMeetingHandler(serverCtx),
				},
				{
					// Chi tiết cuộc họp
					Method:  http.MethodGet,
					Path:    "/meetings/:id",
					Handler: meeting.GetMeetingHandler(serverCtx),
				},
				{
					// Cập nhật lịch họp
					Method:  http.MethodPut,
					Path:    "/meetings/:id",
					Handler: meeting.UpdateMeetingHandler(serverCtx),
				},
				{
					// Hủy cuộc họp
					Method:  http.MethodPatch,
					Path:    "/meetings/:id/cancel",
					Handler: meeting.CancelMeetingHandler(serverCtx),
				},
				{
					// Ghi biên bản họp
					Method:  http.MethodPatch,
					Path:    "/meetings/:id/notes",
					Handler: meeting.UpdateMeetingNotesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					// Danh sách thông báo
					Method:  http.MethodGet,
					Path:    "/notifications",
					Handler: notification.ListNotificationsHandler(serverCtx),
				},
				{
					// Đánh dấu đã đọc
					Method:  http.MethodPatch,
					Path:    "/notifications/:id/read",
					Handler: notification.MarkAsReadHandler(serverCtx),
				},
				{
					// Đánh dấu tất cả đã đọc
					Method:  http.MethodPatch,
					Path:    "/notifications/read-all",
					Handler: notification.MarkAllReadHandler(serverCtx),
				},
				{
					// Cấu hình kênh thông báo (Admin)
					Method:  http.MethodGet,
					Path:    "/notification-config",
					Handler: notification.GetNotificationConfigHandler(serverCtx),
				},
				{
					// Cập nhật cấu hình kênh thông báo (Admin)
					Method:  http.MethodPut,
					Path:    "/notification-config",
					Handler: notification.UpdateNotificationConfigHandler(serverCtx),
				},
				{
					// Tuỳ chọn nhận thông báo của chính mình
					Method:  http.MethodGet,
					Path:    "/notification-settings",
					Handler: notification.GetNotificationSettingsHandler(serverCtx),
				},
				{
					// Cập nhật tuỳ chọn nhận thông báo
					Method:  http.MethodPut,
					Path:    "/notification-settings",
					Handler: notification.UpdateNotificationSettingsHandler(serverCtx),
				},
				{
					// Gửi thông báo thử
					Method:  http.MethodPost,
					Path:    "/notification-settings/test",
					Handler: notification.TestNotificationHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					// Danh sách giai đoạn của dự án
					Method:  http.MethodGet,
					Path:    "/projects/:id/phases",
					Handler: phase.ListPhasesHandler(serverCtx),
				},
				{
					// Tạo giai đoạn
					Method:  http.MethodPost,
					Path:    "/projects/:id/phases",
					Handler: phase.CreatePhaseHandler(serverCtx),
				},
				{
					// Sắp xếp lại giai đoạn
					Method:  http.MethodPatch,
					Path:    "/projects/:id/phases/reorder",
					Handler: phase.ReorderPhasesHandler(serverCtx),
				},
				{
					// Cập nhật giai đoạn
					Method:  http.MethodPut,
					Path:    "/projects/:projectId/phases/:id",
					Handler: phase.UpdatePhaseHandler(serverCtx),
				},
				{
					// Xóa giai đoạn
					Method:  http.MethodDelete,
					Path:    "/projects/:projectId/phases/:id",
					Handler: phase.DeletePhaseHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					// Danh sách dự án
					Method:  http.MethodGet,
					Path:    "/projects",
					Handler: project.ListProjectsHandler(serverCtx),
				},
				{
					// Tạo dự án
					Method:  http.MethodPost,
					Path:    "/projects",
					Handler: project.CreateProjectHandler(serverCtx),
				},
				{
					// Chi tiết dự án
					Method:  http.MethodGet,
					Path:    "/projects/:id",
					Handler: project.GetProjectHandler(serverCtx),
				},
				{
					// Cập nhật dự án
					Method:  http.MethodPut,
					Path:    "/projects/:id",
					Handler: project.UpdateProjectHandler(serverCtx),
				},
				{
					// Xóa dự án
					Method:  http.MethodDelete,
					Path:    "/projects/:id",
					Handler: project.DeleteProjectHandler(serverCtx),
				},
				{
					// Danh sách thành viên dự án
					Method:  http.MethodGet,
					Path:    "/projects/:id/members",
					Handler: project.ListProjectMembersHandler(serverCtx),
				},
				{
					// Thêm thành viên
					Method:  http.MethodPost,
					Path:    "/projects/:id/members",
					Handler: project.AddProjectMemberHandler(serverCtx),
				},
				{
					// Xóa thành viên
					Method:  http.MethodDelete,
					Path:    "/projects/:id/members/:userId",
					Handler: project.RemoveProjectMemberHandler(serverCtx),
				},
				{
					// Override RAG status
					Method:  http.MethodPatch,
					Path:    "/projects/:id/rag",
					Handler: project.UpdateRagHandler(serverCtx),
				},
				{
					// Chỉ định PM cho dự án
					Method:  http.MethodPatch,
					Path:    "/projects/:id/pm",
					Handler: project.SetProjectPmHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					// Danh sách task của dự án
					Method:  http.MethodGet,
					Path:    "/projects/:id/tasks",
					Handler: task.ListTasksHandler(serverCtx),
				},
				{
					// Tạo task
					Method:  http.MethodPost,
					Path:    "/projects/:id/tasks",
					Handler: task.CreateTaskHandler(serverCtx),
				},
				{
					// Chi tiết task
					Method:  http.MethodGet,
					Path:    "/tasks/:id",
					Handler: task.GetTaskHandler(serverCtx),
				},
				{
					// Cập nhật task
					Method:  http.MethodPut,
					Path:    "/tasks/:id",
					Handler: task.UpdateTaskHandler(serverCtx),
				},
				{
					// Xóa task
					Method:  http.MethodDelete,
					Path:    "/tasks/:id",
					Handler: task.DeleteTaskHandler(serverCtx),
				},
				{
					// Duyệt / từ chối task
					Method:  http.MethodPost,
					Path:    "/tasks/:id/approve",
					Handler: task.ApproveTaskHandler(serverCtx),
				},
				{
					// Thêm người thực hiện vào task
					Method:  http.MethodPost,
					Path:    "/tasks/:id/assignees",
					Handler: task.AddTaskAssigneeHandler(serverCtx),
				},
				{
					// Bớt người thực hiện khỏi task
					Method:  http.MethodDelete,
					Path:    "/tasks/:id/assignees/:userId",
					Handler: task.RemoveTaskAssigneeHandler(serverCtx),
				},
				{
					// Đánh dấu phần của tôi đã/chưa xong
					Method:  http.MethodPatch,
					Path:    "/tasks/:id/my-progress",
					Handler: task.MarkMyProgressHandler(serverCtx),
				},
				{
					// Comment trên task
					Method:  http.MethodPost,
					Path:    "/tasks/:id/comments",
					Handler: task.AddCommentHandler(serverCtx),
				},
				{
					// Danh sách comment
					Method:  http.MethodGet,
					Path:    "/tasks/:id/comments",
					Handler: task.ListCommentsHandler(serverCtx),
				},
				{
					// Cập nhật trạng thái task
					Method:  http.MethodPatch,
					Path:    "/tasks/:id/status",
					Handler: task.UpdateTaskStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					// Danh sách workspace
					Method:  http.MethodGet,
					Path:    "/workspaces",
					Handler: workspace.ListWorkspacesHandler(serverCtx),
				},
				{
					// Tạo workspace
					Method:  http.MethodPost,
					Path:    "/workspaces",
					Handler: workspace.CreateWorkspaceHandler(serverCtx),
				},
				{
					// Chi tiết workspace
					Method:  http.MethodGet,
					Path:    "/workspaces/:id",
					Handler: workspace.GetWorkspaceHandler(serverCtx),
				},
				{
					// Cập nhật workspace
					Method:  http.MethodPut,
					Path:    "/workspaces/:id",
					Handler: workspace.UpdateWorkspaceHandler(serverCtx),
				},
				{
					// Xóa workspace
					Method:  http.MethodDelete,
					Path:    "/workspaces/:id",
					Handler: workspace.DeleteWorkspaceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
